apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  labels:
    app: cybersecurity-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cybersecurity-ai
  template:
    metadata:
      labels:
        app: cybersecurity-ai
    spec:
      containers:
      - name: ai-service
        image: cybersecurity-ai:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/app/models"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: cybersecurity-ai
