spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cybersecurity_user_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/cybersecurity_admin_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: your-secret-key-here-make-it-very-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds